services:
  image-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000

      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-gemini-2.5-flash-image-preview}
      - PROMPT_ENHANCEMENT_MODEL=${PROMPT_ENHANCEMENT_MODEL:-gemini-2.5-flash}
      - ENHANCEMENT_PROMPT=${ENHANCEMENT_PROMPT}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
